version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      - db
    volumes:
      - .:/var/www
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: