name: Docker Image CI

on:
  push:
    branches: [ "v4.1.0-beta" ]
  pull_request:
    branches: [ "v4.1.0-beta" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker-compose -f docker-compose.yml up -d --build
    - name: show all the container
      run: sudo docker ps
