name: Docker Image CI

on:
  push:
    branches: [ "4.x" ]
  pull_request:
    branches: [ "4.x" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Go to project dir
      run: ls
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: sudo docker-compose -f docker-compose up -d --build
